### ISSUE TITLE
Pangram: Suggest test case addition

### ISSUE THREAD

**Issue by OrangeMarmalade** [exercism/problem-specifications#1031]
in the case, I only included 24 characters instead of the 26 characters of the alphabet, so there are exceptions where missing any 2 characters other than y and z would make it wrong, but it will still return the result true.

The project should include a test case "bcdefghijklmnopqrstuvwxyzz" to simulate 26 characters but missing any of the first 24 alphabetical characters.

**Comment by rpottsoh** [comment]
@OrangeMarmalade I am not sure I completely understand what you are asking for but I think you are asking for a test case like this to be added to the canonical data.
```json
        {
          "description": "recognizes a letter missing",
          "property": "isPangram",
          "input": "bcdefghijklmnopqrstuvwxyzz",
          "expected": false
        },
```
Would this new case immediately follow `"recognizes a perfect lower case pangram"`?

I have nothing against this case being added.  Others, more familiar with this exercise, should weigh in on this, if they feel this is a good case to be added.

**Comment by rpottsoh** [comment]
@OrangeMarmalade if this issue is still of interest to you I encourage you to open a PR to update the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json) file.

A new policy of placing all input data into an `"input"` object has recently been adopted.  Refer to #996 to learn more.

The `"version"` of the file will need to be updated.  Refer to the [test-data-versioning](https://github.com/exercism/problem-specifications#test-data-versioning) documentation.

I recommend that your PR should consist of two commits.  I don't think the order will matter.  One commit should add the test case you propose.  The second commit should contain the "input" policy changes.

Right now `"version"` is "1.3.0".  It should end up being "1.4.0"

**Comment by OrangeMarmalade** [comment]
Alright I'll do that. And yes the case that you mentioned was the exact case I was talking about.

**Comment by rpottsoh** [comment]
@OrangeMarmalade curious to know if you are still interested in this issue.

**Comment by ErikSchierboom** [comment]
I'm closing this due to a lack of activity. @OrangeMarmalade if you'd like to work on this, let me know and I'll re-open.
