### ISSUE TITLE
Pangram: Add tests for accented characters and non-latin scripts

### ISSUE THREAD

**Issue by isani** [exercism/problem-specifications#1048]
On the csharp track, many pangram solutions use the built-in method IsLetter(char). This method matches more than a-z, which leads to wrong results when the input contains Unicode letters. There are currently no tests that contain letters outside the a-z range, and thus a range of bugs are not caught.

The following strings should be tested as _not_ pangrams (because they don't contain an 'a'):

"äbcdefghijklmnopqrstuvwxyz"
"αbcdefghijklmnopqrstuvwxyz"

The following strings should be tested as pangrams (to ensure input with Unicode isn't just rejected):

"the quick brown fox jumps over the lazy dög"
"the quick brown fox jumps over the lazy dөg"

**Comment by NobbZ** [comment]
Due to very different support of unicode across languages the problem-specifications do only cover ASCII (we haven't agreed if we use traditional 7bit or enhenced 8bit yet ;), some people imply the one, some people imply the other when reading ASCII).

If a language does cope well with Unicode handling, then its in the responsibility of the tracks maintainers to avoid and test against unicode pitfalls of that language.

Can you therefore file a bug at the [C# issue](https://github.com/exercism/csharp/issues) tracker?

cc @exercism/csharp

**Comment by coriolinus** [comment]
This has been discussed before in https://github.com/exercism/problem-specifications/issues/428.

**Comment by NobbZ** [comment]
Oh, it seems as if I am allowed to close here, so I'll move the issue over to C# repo directly.

**Comment by NobbZ** [comment]
Issue moved to [exercism/csharp #502](https://github.com/exercism/csharp/issues/502) via [**ZenHub**](https://www.zenhub.com/)
