### ISSUE TITLE
Can we reword the Parallel Letter Frequency problem in go? 

### ISSUE THREAD

**Issue by PPNC** [exercism/problem-specifications#1132]
I've written this same question on [exercism.io repository](https://github.com/exercism/exercism.io/issues/3713) and was told to open this issue here.

The [Parallel Letter Frequency](http://exercism.io/exercises/go/parallel-letter-frequency/readme) problem uses parallel in its README, but it uses the word concurrent in the tests and [both are not the same thing](https://blog.golang.org/concurrency-is-not-parallelism).  
Can it be rewritten to use the word concurrent instead of parallel?  
This would also make it easier for people to find examples.

**Comment by rpottsoh** [comment]
You are right, they are not the same thing.  However, both `parallel` and `concurrent` are used to describe how to do something via. non-sequential means.  I don't know Go, but would it not be better to update the Go test suite to not use the word concurrent or to perhaps not be so literal in the meaning of the word?  Will something written in Go not utilize more than 1 core (if available) to facilitate parallelism?

I am not stating that I am against changing the documentation for this exercise.  I merely I am not sure if the documentation used by the whole site should be affected or if the change should be localized to a specific track, Go in this instance.

**Comment by tleen** [comment]
I've thought on this a lot when I did the PLF exercise. It is very Go to never use "parallel" and to use "concurrent" for everything. I think the name must stay the same because more people think "parallel" when they are discussing concurrent concepts. Since the problem specifications must remain language neutral any language-specific confusion should be handled at the language level.

I'll open it on the Go track to may any terminology adjustments local.

**Comment by martinfreedman** [comment]
I think the real issue with this exercise is how to actually have tests for parallelism.

**Comment by tleen** [comment]
That is going to be a language specific approach, and may be too difficult to try and implement.
