### ISSUE TITLE
scale-generator: Problem description is unhelpful.

### ISSUE THREAD

**Issue by abeger** [exercism/problem-specifications#1202]
As I mentioned over in https://github.com/exercism/problem-specifications/pull/1156#issuecomment-361069162, the problem specification for the scale-generator both omits critical information and provides a lot of extraneous information. Some examples:

* The difference between uppercase and lowercase tonics is implied, but not explained.
* The table of intervals at the end is completely unnecessary.
* The explanation of non-standard intervals gives unhelpful information (diminished intervals) while not explaining what will be in the problem (what "A" represents in the problems).
* Case is not used consistently for majors and minors in the tonic list.

I'm working on a PR for this.

**Comment by cmccandless** [comment]
[description](https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/description.md)

**Comment by petertseng** [comment]
> Case is not used consistently for majors and minors in the tonic list.

Indeed, currently the cases (uppercase vs lowercase) are strategically selected so that an implementation that strictly follows the README will happen to choose the correct choice of whether to show flats or sharps. If the strategic selection is eliminated, implementations probably have to do a little more work. I'm curious to see how this works out. We'll talk when the PR comes.
