### ISSUE TITLE
All READMEs for exercises where whitespace is significant should have a placeholder for the whitespace

### ISSUE THREAD

**Issue by shingtaklam1324** [exercism/problem-specifications#1208]
For example, the README for crypto-square has this line

> ```
> imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau 
> ```

Which doesn't automatically indicate that there is a whitespace after the `sseoau` when rendered or in many text editors. To make it clearer, it should be like this

> `_` is used for space (ASCII Code 32)
> ```
> imtgdvs_fearwer_mayoogo_anouuio_ntnnlvt_wttddes_aohghn__sseoau_
> ```

**Comment by cmccandless** [comment]
[description](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/description.md)

Personally, I would prefer wrapping text with leading/trailing whitespace in quotes.

> "imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau "

This is common in many shells.

**Comment by coriolinus** [comment]
I strongly prefer the quotes solution over the underscore variant.

**Comment by petertseng** [comment]
Since this issue designates "All READMES for exercises where whitespace is significant", we need to find them.

```
$ git grep ' $' exercises/*/description.md
exercises/crypto-square/description.md:imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau
exercises/ocr-numbers/description.md: _
exercises/ocr-numbers/description.md:|_
exercises/ocr-numbers/description.md:
exercises/ocr-numbers/description.md:    _  _
exercises/ocr-numbers/description.md:
exercises/ocr-numbers/description.md:    _  _
exercises/ocr-numbers/description.md:|_||_ |_
exercises/ocr-numbers/description.md:
exercises/ocr-numbers/description.md: _  _  _
exercises/ocr-numbers/description.md:
exercises/yacht/description.md:    Little Straight 30 points               1 2 3 4 5 scores 30
exercises/yacht/description.md:## Task
```

One by one:

* crypto-square: This issue must be applied. This is important because this describes the expected output.
* ocr-numbers: This describes the input, so failure to notice the trailing whitespaces shouldn't affect the problem. The inputs are going to be in the tests. The lines in question are already in triple backticks. Note that replacement with `_` is going to be undesirable because `_` is a possible character in the input. I recommend that no action need be taken.
* yacht: I recommend removing trailing whitespaces from the description.

**Comment by kytrinyx** [comment]
I believe this is done, as both the crypto-square exercise and the yacht exercise have been updated.
