### ISSUE TITLE
luhn: expectation/description mismatch in canonical test data

### ISSUE THREAD

**Issue by andeemarks** [exercism/problem-specifications#1396]
In problem-specifications/exercises/luhn/canonical-data.json, the following test spec has a mismatch between the stated expectation and the test description

```
    {
      "description": "a simple valid SIN that becomes invalid if reversed",
      "property": "valid",
      "input": {
        "value": "59"
      },
      "expected": true
    },
```
Given the value (a valid luhn number), the description should be changed.

### History 
  In the https://github.com/exercism/kotlin/commit/11faba62f852aac4d773366b19cfc2d7122c6455 commit, these tests had two expectations and better matched the descriptions (testing both the original and reversed state), but this intent was lost when the tests were matched against the canonical test data in commit https://github.com/exercism/kotlin/commit/a2bb40eb9e032c865d5a82a42e93a0a3145a6f9c

### Problem
The JSON schema doesn't seem to test setup described above where ideally two tests are needed to cover the reversal of the test data.

**Comment by petertseng** [comment]
> has a mismatch between the stated expectation and the test description

I don't agree that there is a mismatch.

The reason I say this is because the input "59" is "a simple valid SIN that becomes invalid if reversed", which is exactly as the description says. Nothing in the description indicates that "95" needs to be tested, because "95" would be e.g. "an invalid SIN that becomes valid if reversed".

I would argue that based on https://github.com/exercism/problem-specifications/pull/547#pullrequestreview-21416600 the purpose of that test is to see whether the implementation is selecting the correct set of digits to be doubled. Testing "95" adds no additional value to the test because the implementation that selected the wrong set of digits would either give the correct answer on both "59" and "95" or the wrong answer for both. Thus, only one needs to be tested.

> Given the value (a valid Luhr number), the description should be changed.

I neither agree nor disagree with this. I advise that my comment should not be interpreted to be an argument either for or against changing the description.

> The JSON schema doesn't seem to test setup described above where ideally two tests are needed 

This is true.

**Comment by rpottsoh** [comment]
This is issue isn't driving towards a plan of action.  Feel free to re-open if there is need to further discussion.
