### ISSUE TITLE
Contributing Guide: Anatomy of an Exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#141]
This is stubbed in, and needs to be fleshed out.

https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#anatomy-of-an-exercise

**Comment by petertseng** [comment]
Well, that documentation moved in https://github.com/exercism/problem-specifications/pull/843 -> https://github.com/exercism/docs/pull/57, but it is still true that everything in that document is still a TODO. So now I would recommend reopening https://github.com/exercism/docs/issues/26, which I will, instead of keeping this issue here.

**Comment by petertseng** [comment]
Okay, maybe not reopen the same, but something in docs repo.
