### ISSUE TITLE
dnd-character: check ability for proper statistical properties

### ISSUE THREAD

**Issue by AnAccountForReportingBugs** [exercism/problem-specifications#1419]
While watching the progress of the dnd-character pull request in the Python track, I noticed that the initial idea for the dice roll was simply: `return random.randint(3, 18)`.  The problem with that is it does not have the same statistical properties as the required roll of 4d6D1.  To compare:

Roll | Mean | S. Stdev.
------------ | ------------- | -------------
Randint(3, 18) | 10.5 | ~4.75
3d6 | 10.5 | ~2.95
4d6D1 | 12.25 | ~2.85

Therefore, I think implementation tests should check that for a large enough sample (~1000, but the larger the better), the standard deviation and mean of the data are close to the expected values.  Below are ways of calculating them (written in rough Python) that may be generalized to languages without such calculations in the standard library.

    def average(data):
        length = 0
        total = 0
        for x in data:
            length += 1
            total += x
        return total / length

    def stdev(data, average):
        total = 0
        length = 0
        for x in data:
            total += (x - average) ** 2
            length += 1
        return sqrt(total / (length - 1))

    def sqrt(number):
        guess = 0
        while guess ** 2 < number:
            guess += 1
        while not (-0.000000001 <= guess**2 - number <= 0.000000001):
            guess = (guess + (number/guess) )/2
        return guess

**Comment by coriolinus** [comment]
We've floated the idea of performing statistical analysis of randomness
before. In general the consensus was that while statistical analysis of
randomness can be useful in many production environments, it isn't a good
fit for Exercism:

- it depends on large numbers of repetitions. Our unit tests should be "too
fast to notice", which as a practical rule of thumb means that no single
test should take more than 100 ms or so with a good implementation. It may
be possible to perform this analysis within that speed limit, but it's
already starting to approach the edge of the envelope.
- it is prone to false positives: failure when the implementation was
correct but happened to generate an anomalous sequence.
- perhaps most importantly, we have a mentor system of volunteers examining
the code in question. Statistical analysis here should not be necessary,
because humans should already be looking for this case.

**Comment by sshine** [comment]
I'm happy that you bring this to discussion.

I'm writing this as I'm waiting for the Haskell track's CI to complete so I can merge. It takes about 8½ minutes. So on the grounds of keeping the test suite fast, I'm reluctant but not refusing to introduce statistical property tests.

I think testing for mean and std. dev. would be sufficient to hint that the student has got the wrong distribution, without testing the entire distribution. (As you highlight, three typical attempted solutions have different means and std. devs.) But since the distribution is both discrete and finite, if this were mission-critical software, I would also like to test that the distribution is actually correct, not just the mean and the std. dev.

I think the most important property of such a test, more important than speed of execution, is that it isn't flaky: The test will run over and over again thousands of times, so you want to somehow pick a number of times and an error margin such that the odds of a negative failure is many times smaller than the number of expected runs. Or set the number quite low and fix the seed, which somehow doesn't feel as honest.

**Comment by sshine** [comment]
With which frequency will this test randomly fail?

**Comment by bitfield** [comment]
I agree that _if you're modelling dice rolls_, distribution is very important. It's also pretty difficult to test automatically, reliably, quickly. It seems like this would be more of a candidate for mentor notes on the individual tracks than any kind of test cases—but I'd be happy to be proved wrong by a 100% reliable test that executes in <100ms.

**Comment by cmccandless** [comment]
> but I'd be happy to be proved wrong by a 100% reliable test that executes in <100ms.

For interpreted languages such as Python, I would accept <1s.

**Comment by AnAccountForReportingBugs** [comment]
Knowing how often these tests will error is heavily dependent on the underlying random bytes used to construct the numbers.  Assuming that the language library has a good PRNG built in (like Python or Ruby) or uses a good source (like /dev/urandom), then the chances of the 4d6D1 roll failing is extremely low due to its negative skew and Z score for failing.  There is a small chance of a randint(3, 18) passing both tests simultaneously, but that is highly unlikely if the RNG below is unbiased.  Another benefit is that a faulty modular transformation of random bytes (if a person has to deal with those) will have a positive skew, which makes them more likely to fail.

**Comment by sshine** [comment]
> With which frequency will this test randomly fail?

For a given implementation, this question can be answered with a number.

Perhaps this issue should stand as a reference to those who seek to add such a test to a language track.

**Comment by AnAccountForReportingBugs** [comment]
I'm not sure of your point.  But if I understand it, it is impossible for any one person to answer.  I don't know how many languages and implementations exist.  For example, there are more than 10 implementations of Python, more than 10 of Common Lisp, at least 5 of Ruby.

However, like I said, assuming they have a good randint implementation (such as a modern LSFR on the vein of Mersenne Twisters, WELL, xorshift+, or modern LFGs, let alone most CSRNGs), then the chances of them failing both tests are literally so small that the doing a double-precision calculation resulted in the FPE drowning out the signal.

A truly random selection from a FIPS 140-2 compliant source would fail at least one test is between 1.003834*10^-9 and 6.568*10^-3045.  Of course, that depends on the actual source and how paranoid they are in terms of output quality.

**Comment by sshine** [comment]
My point is not that PRNGs vary in insignificant ways. 

Given a uniform (pseudo-)random function from 1 to 6, give me, *statistically*, the *frequency* with which one's test fails to be within some acceptable variation of e.g. the expected average. If this frequency is big enough, I'd accept a test that is technically flaky.

Specifying that number would make me much more susceptible to accept a PR to a statistical test in a test framework.

**Comment by AnAccountForReportingBugs** [comment]
I've provided numbers on multiple occasions, but apparently they aren't good enough.  Will find another hill to die on.
