### ISSUE TITLE
rest-api: Missing test case of lender owes borrower same as new loan

### ISSUE THREAD

**Issue by turnkey-commerce** [exercism/problem-specifications#1439]
rest-api is missing a test case when the previous lender becomes the borrower and borrows the same amount as the current balance thus zeroing the balances and removing the respective owes and owed_by for both parties.  This exercises some necessary code for this case that was previously not covered. Have already tested this and will submit a pull-request to add the new test.

**Comment by NobbZ** [comment]
I'm strictly against zeroing each balance.

There might be reasons like taxes, interests, pay-back rate that make it necessary to strictly treat each loan as separate entites instead of simply calculating differences.

**Comment by petertseng** [comment]
> There might be reasons like taxes, interests, pay-back rate that make it necessary to strictly treat each loan as separate entites instead of simply calculating differences.

Because it is highly likely that this would require a change to the two existing test cases "lender owes borrower" and "lender owes borrower less than new loan" https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json#L258-L361 , if that is true I encourage parties interested in that to make a new issue and/or pull request for that change.

**Comment by turnkey-commerce** [comment]
Also as I edited in the PR and noted by @petertseng it is self-consistent with the previous two exercises that already change the balances, it is just changing it to reflect the actual state of 0.
