### ISSUE TITLE
Rename resistor-colors

### ISSUE THREAD

**Issue by iHiD** [exercism/problem-specifications#1495]
Hello :)

We have two new exercises:
- resistor-color
- resistor-colors

I'm uncomfortable with how close the names are. It is marginally confusing generally, and for someone less familiar with English, I think just having the `s` changed is not enough.

I propose renaming the second exercise to `resistor-color-pairs`. I'm not attached to that, but I just want some proposal down as a default if no-one can come up with anything better :)

Once this is agreed, I'll merge https://github.com/exercism/website-icons/issues/25

(cc @F3PiX @ErikSchierboom who came up with the exercise)

**Comment by ErikSchierboom** [comment]
I understand the confusion. Personally, I don't have a preference for any other name, so I'll leave that to @F3PiX :)

**Comment by F3PiX** [comment]
I agree it's confusing. I'm looking ahead at the rest of the series, and it would be best if the sequence is clear, looking only at the names.
Therefore I'd prefer to change both names:
- Resistor Color -> Resistor Single Color
- Resistor Colors -> Resistor Color Duo (for people knowing Resistors "pairs" is probably confusing.)

The next will be about, you guess that, 3 colors, so that can be Restistor Color Trio, or something else that indicates 3.   

How about this?

**Comment by iHiD** [comment]
I like "Resistor Color Duo" and "Resistor Color Trio" but I think "Resistor Single Color" is a little functional. I'd happily just leave that as "Resistor Color" and change the others as you suggested.

I'd also rather not change the first as it's live exercise on lots of tracks, so renaming it now is hard.

**Comment by iHiD** [comment]
This seems to be positively recieved. Presuming there's no objections, could we get `resistor-colors` changed to `resistor-color-duo` on the tracks that have implemented it pls (just change the title and slug, but not the uuid) and I'll get the icon merged :)

**Comment by cmccandless** [comment]
I created #1502 for this.

Also, Python track implementation has been renamed. I regenerated the README using the changes made in #1502.

**Comment by iHiD** [comment]
So I think it's these tracks. Sample PR is [here](https://github.com/exercism/problem-specifications/pull/1502).

- [ ] Python (cc @exercism/python)
- [ ] Haskell (cc @exercism/haskell)
- [ ] JavaScript (cc @exercism/javascript)
- [ ] Pharo (cc @exercism/pharo-smalltalk )
- [ ] Ruby (cc @exercism/ruby )

**Comment by SleeplessByte** [comment]
Maintainers: don't forget to update `website-copy` if you have mentor notes already.

**Comment by kotp** [comment]
> I like "Resistor Color Duo" and "Resistor Color Trio" but I think "Resistor Single Color" is a little functional. I'd happily just leave that as "Resistor Color" and change the others as you suggested.

Though there may be some value in doing so as it does hint to those that may feel like expanding on the color exercise that there are more coming up, or even to limit it (for some unknown reason) to a single color.

**Comment by pgaspar** [comment]
Process question: what should be merged first? The problem specifications PR (#1502) or the Track updates? I'm holding off merging my Ruby track changes because they refer to the specific commit on #1502 (8b44ce1) in [this line](https://github.com/exercism/ruby/pull/955/files#diff-af9ceb3d87e2c32c03f33f9c16802b4aR4).

So it seems to make sense to merge #1502 beforehand, right?

cc @kytrinyx

**Comment by rpottsoh** [comment]
Correct.  Update problem specification first.

**Comment by tejasbubane** [comment]
There's an issue in Javascript https://github.com/exercism/javascript/issues/664 with the renaming. Anyone knows what's wrong here?

**Comment by SleeplessByte** [comment]
@tejasbubane I have the same as you: no error for me. Perhaps propagation / caching issue?

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/622

**Comment by macta** [comment]
Did I accidently close this - by referencing it (I think it stays open for Haskell)?

**Comment by tejasbubane** [comment]
Haskell is done. So I guess this can be closed now.

**Comment by iHiD** [comment]
Thanks y'all!
