### ISSUE TITLE
Largest Series Product: why LargestSeriesProduct(, 0) wants 1 ?

### ISSUE THREAD

**Issue by b10s** [exercism/problem-specifications#1638]
Hi,

the `LargestSeriesProduct(, 0)` wants `1` as a result but product of nothing can not be 1, isn't it ?

**Comment by SaschaMann** [comment]
The canonical data explains it: https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/canonical-data.json#L107:L120

Wikipedia has a more in-depth justification for why the empty product is 1 by convention: https://en.wikipedia.org/wiki/Empty_product

**Comment by b10s** [comment]
@SaschaMann wiki says: `In mathematics, an empty product, is by convention zero` as my naive expectation:

<img width="1008" alt="Screen Shot 2020-02-19 at 0 22 01" src="https://user-images.githubusercontent.com/4618288/74749731-ef8c7180-52ad-11ea-9ed3-ed975766c436.png">

Did I miss something?

**Comment by SaschaMann** [comment]
> Did I miss something?

The highlighted part below refers to the empty product. The rest of the sentence is about the empty sum.

> **In mathematics, an empty product, or nullary product, is the result of multiplying no factors. It is by convention equal to the multiplicative identity** (assuming there is an identity for the multiplication operation in question), just as the empty sum—the result of adding no numbers—is by convention zero, or the additive identity.

The multiplicative identity for real numbers is `1` because for any real number x, `1 * x = x`.

The justification is outlined [below](https://en.wikipedia.org/wiki/Empty_product#Justification):

> Allowing a "product" with only one or zero factors reduces the number of cases to be considered in many mathematical formulas. Such "products" are natural starting points in induction proofs, as well as in algorithms. For these reasons, the "empty product is one" convention is common practice in mathematics and computer programming.

In other words, it's 1 by convention because then it doesn't break things without requiring special cases. It's also consistent with other behaviour that the English Wikipedia article doesn't mention, for example in combinatorics. It's a convenient definition to have.

**Comment by yawpitch** [comment]
That wikipedia article's first line could really use some editing for grammar.

**Comment by b10s** [comment]
That is amazing!
Thank you for explaining and sorry for bothering
