### ISSUE TITLE
Clock exercise improvements

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#166]
I've been reviewing a lot of submissions for the Go implementation of Clock, and I'm seeing a few interesting edge cases:
1. Sometimes there's mutation happening in the display method instead of the add, so you might have two copies of clock that are identical, add 1440 minutes to one, 2880 minutes to the other, and now they display the same value, but are not equal.
2. They only account for one adjustment in either direction, meaning that if someone said add 1,000,000 minutes, then the clock would not end up with a valid display time.

I think that we should have test cases that go much father outside of the valid values, and I also think that we should test equality after adding values.

**Comment by kytrinyx** [comment]
note to self: Time(0,-60) == Time(23,0)

**Comment by kytrinyx** [comment]
The canonical test data was improved in this PR: https://github.com/exercism/x-common/pull/210

**Comment by kotp** [comment]
The json file has places were we modify by more than a day... but the problem comes when there is a unique situation where a parenthesised note shows up.  Though it may be interesting that 1500 minutes is 25 hours, we really don't need to have that in the file that is meant to simplify the generation of tests.

It complicates what we need to do in order to make valid test "titles" in some languages, or in using specific styles.

**Comment by kytrinyx** [comment]
Agreed--I'm fine with ditching the parentheses in the descriptions.

**Comment by petertseng** [comment]
it's not useful (there is no action for us to take) to leave this issue open.

However, individuals interested in how tracks should keep up-to-date with problem-specifications should look at https://github.com/exercism/problem-specifications/issues/524 .

Note that the situation has gotten a lot better since the days of this issue, since the JSON file has  a version now.
