### ISSUE TITLE
Incorrect Instructions in Pythagorean Triplets on Julia Track

### ISSUE THREAD

**Issue by MpdWalsh** [exercism/problem-specifications#1672]
I'm going to preface this with the warning that I'm being incredibly pedantic.

The instructions say that the condition `a < b < c` must be satisfied. However, when I was browsing (okay, skimming) the Wikipedia page on Pythagorean Triplets, I couldn't find that condition. I believe it should say `a <= b < c`.

I wrote a script to find values for n where a == b and found this:
n = 3.18281039e8
a = 9.3222358e7, c = 131836323

I verified that it satisfies the 2*(a^2) = c^2 on Wolfram Alpha: https://www.wolframalpha.com/input/?i=2+*+%289.3222358e7%5E2%29+%3D%3D+131836323%5E2

Obviously, there's no need to add 3.18281039e8 to the test suite. I've been running my solution for about 10 minutes now and my laptop is very hot. No end in sight.

So, yeah. `a <= b < c`. 
< /pedantry>

**Comment by iHiD** [comment]
Moving this to Problem Specs for wider discussion as I don't think it's Julia-specific (but correct me if I'm wrong)

**Comment by cmccandless** [comment]
All non-primitive triplets are multiples of a primitive triplet. So a quick pseudo-proof:

Let [a, b, c] be a primitive triplet, where a^2 + b^2 = c^c and a < b < c.
For all integer n >= 1, For all [x, y, z], let x = a * n, y = b * n, and z = c * n.
If a < b, a * n < b * n, so x < y.

**Comment by petertseng** [comment]
I will immediately mark this off-topic upon posting it, since it is off-topic to the main issue being discussed. I suggest you mark any replies to me as off-topic as well.

>  https://www.wolframalpha.com/input/?i=2+*+%289.3222358e7%5E2%29+%3D%3D+131836323%5E2

That is an interesting link, and I agree that it answers true. But we can intuitively see by checking the ones digit that it cannot be true. the number on the LHS that ends in 8 gets squared, resulting in a number that ends in 4. Then it gets doubled, resulting in a number that ends in 8. The number on the RHS that ends in 3 gets squared, resulting in a number that ends in 9. So the two sides cannot be equal.

What if we instead ask Wolfram Alpha a slightly different question? You would agree with me that [9.3222358e7 should be equal to 93222358](https://www.wolframalpha.com/input/?i=93222358+%3D%3D+9.3222358e7), yes?

[https://www.wolframalpha.com/input/?i=2+*+(93222358^2)+%3D%3D+131836323^2](https://www.wolframalpha.com/input/?i=2+*+%2893222358%5E2%29+%3D%3D+131836323%5E2)

That says false.

We're left to ask ourselves why Wolfram Alpha would have made this mistake with the original query. That I do not know. Maybe it was close enough in floating point.

**Comment by petertseng** [comment]
EBWODP:

It appears the answer I was looking for is in https://mathematica.stackexchange.com/questions/76896/different-floating-point-numbers-equal. Also observe that Wolfram Alpha declares that [999999999.1 == 999999999.11](https://www.wolframalpha.com/input/?i=999999999.1+%3D%3D+999999999.11)

**Comment by MpdWalsh** [comment]
So here's what I did:
`c^2 == a^2 + b^2`
if a==b then
`c^2 == a^2 + a^2`
`c^2 == 2 * a^2`
`c^2 \ 2 == a^2`
`a == sqrt(c^2/2)` This is what I wrote in my script. I used a loop to increment the value of `c`. To check if `a` was a whole number, I compared `a` to the result of rounding `a`. It was a hack, I know.

If we go a step further, however:
`a == sqrt(c^2) / sqrt(2)`

Dividing a non-zero number by an irrational (root of 2), will yield an irrational (proof here: https://www.answers.com/Q/Is_a_rational_number_divided_by_an_irrational_number_always_irrational) and, according to the Wiki on Pythagorean Triple's, no triangle with a non-integer side is also a Pythagorean Triple.

So, I have to agree with @petertseng in that there was a rounding error somewhere. Probably if you go to a high enough multiple of sqrt(2).

**Comment by iHiD** [comment]
Thanks all :)
