### ISSUE TITLE
exercises with inconsistent input keys per property

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#1764]
report: 

grade-school has inconsistent roster keys:

* 5 cases have ["students"]
* 1 cases have ["students", "desiredGrade"]

simple-cipher has inconsistent encode keys:

* 1 cases have ["plaintext"]
* 4 cases have ["key", "plaintext"]

simple-cipher has inconsistent decode keys:

* 1 cases have ["ciphertext"]
* 1 cases have ["plaintext", "ciphertext"]
* 3 cases have ["key", "ciphertext"]
* 1 cases have ["key", "plaintext", "ciphertext"]

rest-api has inconsistent get keys:

* 1 cases have ["database", "url"]
* 1 cases have ["database", "url", "payload"]

This is a report only, and the report renders no judgment. Some of these might be okay. Judgment may be used on whether any of these should be rectified. If any of these should be rectified, please open separate issues.

Code that generates:

```ruby
require 'json'

def cases(h)
  # top-level won't have a description, but all lower levels will.
  # therefore we have to unconditionally flat_map cases on the top level.
  # on lower levels we either flat_map cases or just return individuals.
  cases = ->(hh, path = [].freeze) {
    hh['cases']&.flat_map { |c|
      cases[c, (path + [hh['description'].freeze]).freeze]
    } || [hh.merge(path: path)]
  }
  h['cases'].flat_map(&cases)
end


Dir.glob("#{__dir__}/exercises/*/canonical-data.json") { |f|
  exercise = File.basename(File.dirname(f))
  props = cases(JSON.parse(File.read(f))).group_by { |c| c['property'] }
  props.each { |prop, cases|
    keys = cases.map { |c| c['input'].keys }.tally
    next if keys.size == 1

    puts "#{exercise} has inconsistent #{prop} keys:"
    puts
    keys.each { |ks, count|
      puts "* #{count} cases have #{ks}"
    }
    puts
  }
}
```

**Comment by ErikSchierboom** [comment]
I think the grade-school issue is an actual mistake in the canonical data. It looks to be a recent addition (https://github.com/exercism/problem-specifications/commit/03529d08e743599bf42ccd811c3f46a3ea79ce7c) and it appears to introduce an error scenario, but without using an expected `error` value.

The simple-cipher cases are actually a bit of a mess. You can see that we struggled to encode rules that don't use fixed data but depends on some other function result. Might be good to overhaul this sometime.

The rest-api case could be fixed by adding an empty object for the payload. This might be good for consistency although there is something to be said for omitting the payload when it is not present.
