### ISSUE TITLE
saddle-points: sorting?

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/problem-specifications#1785]
It looks to me like test cases that return multiple saddle points seem to sort them by row number ascending first, then column number ascending.

There is one test case that doesn't follow that sorting:
https://github.com/exercism/problem-specifications/blob/3a0ee21919fd19b73d985ee2cd70f768e7388229/exercises/saddle-points/canonical-data.json#L130-L144

Is my assumption about the desired sorting wrong, or is this test case wrong and needs to be fixed?

**Comment by SleeplessByte** [comment]
Good question. I think I might have just blindly copied this :p

**Comment by petertseng** [comment]
Sections of this message: My overall recommendation, why, applicability to other problem specifications

My overall recommendation for whether the two elements in the cited case should be reordered: Yes, if desired by any implementing track.

---

Why:

Doing so would probably be appreciated by some implementing tracks, and would not jeopardise the case's correctness.

Leaving it as-is would also not jeopardise the case's correctness.

Since nothing about "find the saddle points" indicates that the saddle points should have any ordering to them, fundamentally the answer is an unordered collection.

So, tests in an implementing track should only be obligated to check that a student implementation produces the same elements, without regard to their ordering.
The approach an implementing track takes to achieve this is left to the person writing the tests.
Reordering all cases to have a consistent ordering will enable one approach (sort the answer produced by the student; do nothing to the answer in the canonical data), and I do not expect it to jeopardise any other approach.
Thus, it should be mostly beneficial, with the only costs being the time required of implementing tracks' maintainers to process the new case which `reimplements` the old one.

---

Other problem specifications:

Indeed, this is an interesting question for all problems where the answer is an unordered collection, since we have no choice but to have some ordering in the JSON.
Such problems include, but are not limited to:

* anagram
* dominoes
* poker
* pythagorean-triplets
* saddle-points

If we find a good way to signal to implementing tracks that the answer is an unordered collection, at least those five problems could all benefit from that.

Note that grade-school is deliberately not included in this list, because its description imposes a sort order.

**Comment by petertseng** [comment]
EBWODP: Add go-counting to list of problems whose answers are unordered collections.

**Comment by SleeplessByte** [comment]
Since comments are not breaking, we **could** add comments to everything to talk about the order?
