### ISSUE TITLE
[markdown] Update header test to work from h1 to h6

### ISSUE THREAD

**Issue by gsilvapt** [exercism/problem-specifications#1812]
Hello everyone,

I was reviewing a markdown solution and noticed the tests for this challenge are for a h1, h2 and h6. I believe it would be ideal to test for all other headers in between to ensure users will write code that can parse all headers. 
Newcomers will probably go with a method for each header, the ideal solution is something more dynamic that mentors can introduce them to.

Before opening a PR, I decided to bring this up to discussion - [which I didn't when I created this PR](https://github.com/exercism/python/pull/2457) :man_facepalming:  

In the PR above, you can see what I was looking for to this specific test. Kindly let me know if this makes sense for this track and if I can move forward with this update - I can link the PR with this issue to close it afterwards.

Thank you for your time

**Comment by SleeplessByte** [comment]
Hi Gustavo!

I can think of three reasons we would want to add tests for `h3`, `h4`, `h5` and maybe even `h7`:
- Dealing with `h3` - `h5` is different than `h1`, `h2`, `h6`. If this is the case, adding the test cases is probably beneficial to everyone.
- You've seen that because people are only dealing with `h1`, `h2`, and `h6` they don't handle all the edge cases, or they handle `h6` as an edge case. If this is the case, adding the test cases is likely beneficial to multiple tracks.
- Completionism. We have quite a few exercises where extra tests are added to "complete" the set. This is fine too, but has a different impact.

It help if you can indicate what's going on, perhaps with code examples (how people write it before adding the extra tests, and after), if it's the first or the second case.

If you get some agreement here, you can open a PR here adding the new tests, and usually if at least one other track - at least three people - agree with the change being (at least a little bit) beneficial, it will be merged. The change doesn't need to be beneficial to all tracks, or everyone.

**Comment by gsilvapt** [comment]
Thanks for the help, @SleeplessByte!

Let me then try to go deeper into the problem I am trying to raise and how can tests solve the issue.

I saw one user solution for this that was something like the following. The highlight is that he wrote one regular expression for each header depth level announced:

```python
def parse_h1(line):
       return re.sub(r"^# (.*)", r"<h1>\1</h1>", line)


def parse_h2():
       return re.sub(r"^## (.*)", r"<h2>\1</h2>", line)


def parse_h6():
       return re.sub(r"^###### (.*)", r"<h6>\1</h6>", line)
```

I think this part of the exercise, to parse headers that can go from 1 to 7, is great to apply some abstract thinking to solve the problem. Furthermore, we know regular expressions can be more dynamic than the above and take variable length expressions. In this case at hands, we can write one that matches when there are 1 or up to 7 `#` symbols together.
In the case of Python, we can define functions inside functions, but for all other tracks a similar implementation is likely possible:

```python
def parse_header(line):
    def replacement(match):
        hashes, text = match.groups()
        num = len(hashes)
        return f'<h{num}>{text}</h{num}>'
    return re.sub(r'^(#{1,7}) (.*)', replacement, line)
```

This snippet comes originally from the community notes for this exercise and makes use of a more dynamic regular expression, it is less code overall, cleaner and nicer to read, IMO. 
My suggestion here is to create tests for all headers (despite only announcing h1, h2 and h6) for completeness and to raise awareness of good problem solving practices - Don't repeat yourself. If a trainer focus on h1, h2 and h6, the suite should fail.


Hope this clarifies better what is the intention here and hope tracks maintainers find this useful to enforce good coding practices.

Thank you for your time reviewing this so far :pray:

**Comment by SleeplessByte** [comment]
Note that h7 doesn't exist in the HTML spec so I expect it to not exist in markdown. For generic implementations you probably want a test that checks that 0 and 7 don't yield a valid hx result.

Everything else makes sense to me. If adding more test cases makes it more likely to come with a general purpose solution, I would go for it (a pr on this repo).
