### ISSUE TITLE
`flatten-array` Proposal of changing description and adding additional test cases

### ISSUE THREAD

**Issue by kwchang0831** [exercism/problem-specifications#1951]
# 1. Proposing to update exercise's description

## Statement
The `flatten-array` [exercise](https://exercism.org/tracks/elixir/exercises/flatten-array)'s Instructions stated
> Take a nested list and return a single flattened list with all values except nil/null.
>
>The challenge is to write a function that accepts an arbitrarily-deep nested list-like structure and returns a flattened structure without any nil/null values.
>
>For Example
>input: [1,[2,3,null,4],[null],5]
>output: [1,2,3,4,5]

According to [Elixir docs - #data-types](https://hexdocs.pm/elixir/1.13.2/syntax-reference.html#data-types), there is no `null` data type. Unlike `nil` is treated as `false` in the Boolean contexts, the `null` has no further meaning. We should not be referring `null` unless the exercise's original intent was to detect `:null` or `Null` atom and remove them from the list. Otherwise, it might be confusing. 

IMHO making sure the exercise's description is consistent with [Exercism Concept - Nil](https://exercism.org/tracks/elixir/concepts/nil) is desirable.

Moreover, the example input is invalid.
```elixir
# The following input will raise CompileError: undefined function null/0 (there is no such import)
[1,[2,3,null,4],[null],5]
```

## Proposed Solution
- Take out `null` words in the instructions
- Replace `null` in input to `nil` 

# 2. Proposing to add additional test cases

## Statement
Suppose I have the following solution to the exercise
```elixir
defmodule FlattenArray do
  @doc """
    Accept a list and return the list flattened without nil values.
 
    ## Examples
 
      iex> FlattenArray.flatten([1, [2], 3, nil])
      [1,2,3]
 
      iex> FlattenArray.flatten([nil, nil])
      []
 
  """
  @spec flatten(list) :: list
  def flatten(list), do: _flatten(list, [])
  defp _flatten([h|t], tail) when is_nil(h), do: tail
  defp _flatten([h|t], tail) when is_list(h), do: _flatten(h, _flatten(t, tail))
  defp _flatten([h|t], tail), do: [h|_flatten(t, tail)]
  defp _flatten([], tail), do: tail
end
```
The solution will pass. However, this is an incorrect solution.

Given the following input `[nil, nil, 2]`, the expected answer should be `[2]`
The above solution will output `[]` which is incorrect.

## Proposed Solution
- Add additional test cases for example
  - consecutive nil values in the front of input list: `[nil, nil, 3]`
  - consecutive nil values in the middle of input list: `[1, nil, nil, 4]`
  
# Comments
If my proposal is accepted, I am willing to create PR to both [exercism/problem-specifications](https://github.com/exercism/problem-specifications) and [exercism/elixir](https://github.com/exercism/elixir). 
Thanks.

**Comment by siebenschlaefer** [comment]
> According to [Elixir docs - #data-types](https://hexdocs.pm/elixir/1.13.2/syntax-reference.html#data-types), there is no null data type.

This is the language-independent problem specification. I don't think we will find a keyword that works in all languages. C, C++, and JavaScript have `null`, Python doesn't have `nil` or `null` but `None`.

IMHO the question is: Is the description easy to understand? If not we should probably clarify what `null` means. Or each track where that is a problem should change the description to match the language.

**Comment by petertseng** [comment]
Regardless of whether proposal 1 (to change the stated name of the value that should not be present in final list) should be accepted, proposal 2 (to add two cases with consecutive instances of the value that should not be present) is useful. I am in support of proposal 2 (to add two cases with consecutive instances of the value that should not be present).

Of course, when adding these additional cases to JSON, we keep in mind that JSON **must** use `null`, regardless of what the description says. It is the language track's job to translate the JSON `null` in the appropriate way for the target language.

If we wanted language independence for `flatten-array` and thus not to make specific reference to either `null`, `nil`, `None`, or `Nothing`, then a way to do so is to instead take as a parameter the value that should not be present. So `flatten(array: [[1, 2], [0], [3, 0]], remove: 0)` will result in `[1, 2, 3]`. I would understand arguments that this exercise is then no longer about flattening an array but also filtering it, but that ship has already sailed since we're already filtering a value out in the current version of the exercise.

**Comment by kwchang0831** [comment]
Thanks so much for both your feedback.

Since proposal 1 is arguable, I have created a PR #1953 only for proposal 2 for the reviews.

**Comment by kwchang0831** [comment]
Thanks all. 

Both PRs for 2nd proposal have been merged:
- #1953
- [exercism/elixir#1060](https://github.com/exercism/elixir/pull/1060)
