### ISSUE TITLE
Should queen-attack creation tests be improved?

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/problem-specifications#396]
I was working on creating a ruby generator for the queen attack problem, when I noticed that the tests for creating a queen attack problem only mention the position of one of the queens. This is cumbersome, because it means we need to have two cases for the generators, one that generates tests based on data for one queen and one that generates tests for both the white and the black queen. I suggest we change the generator code to _always_ specify the position of _both_ the white _and_ the black queen.

This also allows us to consistently deal with the error case where the white and black queen occupy the same space (presumably this _is_ an error state).

**Comment by IanWhitney** [comment]
The tests you're referencing are the ones in the [create](https://github.com/exercism/x-common/blob/54a0fb191cd6eb9ce92507ab6a0bc45cf44e695f/exercises/queen-attack/canonical-data.json#L11) section, right?

I'm not sure you need to create 2 queens here, though it probably depends on the API you're implementing. This test structure came out of how we did things [in Rust](https://github.com/exercism/xrust/blob/e2289bbd7d4eee79807cc1251c69e8c7f75523a1/exercises/queen-attack/tests/queen-attack.rs) and our approach was to create `ChessPosition` instances that could be validated independently of a chess piece.

And the current test suite never checks for pieces being on the same spot. I know that some tracks currently check for that, but I decided to leave those tests out because they went beyond the problem as written & verged to writing a 'real' chess simulator. Like the test description says, tests like this can be offered as 'extra credit', but I didn't see them as part of the core problem.

**Comment by ErikSchierboom** [comment]
Looking at the [current canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/queen-attack/canonical-data.json), the create section is indeed focused on one queen. I'm not sure it is _that_ big of hurdle for generators to support, although I can see why two queens could be slightly easier. 

With the lack of comments on this the last 6 years, I'm closing this issue. If you feel strongly about keeping this issue open, feel free to re-open.
