### ISSUE TITLE
Update tests of Luhn

### ISSUE THREAD

**Issue by IanWhitney** [exercism/problem-specifications#491]
This is the blazon tracking issue for the updates to Luhn's canonical tests. Those changes were made in #474.

**Comment by stevejb71** [comment]
The current description implies that "0" is a valid string, according to the tests it is not.
I've updated the description to follow the tests, and also added a 0 length string test.

**Comment by petertseng** [comment]
it's not useful (there is no action for us to take) to leave this issue open.

However, individuals interested in how tracks should keep up-to-date with problem-specifications should look at https://github.com/exercism/problem-specifications/issues/524 .

Note that the situation has gotten a lot better since the days of this issue, since the JSON file has  a version now.
