### ISSUE TITLE
kindergarten-garden: inconsistency between description and canonical tests

### ISSUE THREAD

**Issue by rstockbridge** [exercism/problem-specifications#856]
The description states
>There are 12 children in the class:
>- Alice, Bob, Charlie, David,
>- Eve, Fred, Ginny, Harriet,
>- Ileana, Joseph, Kincaid, and Larry.

However, there are several tests that involve custom students. The description does not make clear that the solution will need to be generalized beyond the given class of students.

I think either the description should be updated to match the tests or vice versa.

**Comment by petertseng** [comment]
I agree in #659.

My agreement is despite the fact that this is how the exercise has always been since https://github.com/exercism/exercism.io/commit/2d50787a3b4ca3eea70a5591b8c63e3fbd997517 (with the test in question called `SurpriseTest`, implying that its absence in the description indicates that it is supposed to be a surprise requirement). This is because ever since https://github.com/exercism/go/issues/189 I have preferred that the description describe the requirements accurately. Granted, the omission might not force as much extra work, but it would probably still force some nonzero amount.

**Comment by rstockbridge** [comment]
Thanks @petertseng for your comment. I'm closing this issue since you have previously documented it.
